import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./styles/globals.css";
import { Providers } from "@/lib/providers";

const IBMPlexSans = IBM_Plex_Sans({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "TestBit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={IBMPlexSans.className}>{children}</body>
      </html>
    </Providers>
  );
}
